version: "3.9"

volumes:
  mysql-store:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src/:/app
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: store
      MYSQL_USER: store_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  db-testing:
    build:
      context: .
      dockerfile: ./docker/db-testing/Dockerfile
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: store_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: 'Asia/Tokyo'

volumes:
  mysql-volume:
